[package]
name = "gensmusic"
version = "0.1.0"
edition = "2021"

[dependencies]
audiotags = "0.5.0"
eframe = "0.28.1"
egui_extras = "0.28.1"
raplay = { git = "https://github.com/gennyble/raplay", branch = "genny", version = "0.3.5", default-features = false }
